from app.bot.commands.start_command import start
from app.bot.commands.aries_command import aries
from app.bot.commands.tauro_command import tauro
from app.bot.commands.geminis_command import geminis
from app.bot.commands.cancer_command import cancer
from app.bot.commands.leo_command import leo
from app.bot.commands.virgo_command import virgo
from app.bot.commands.libra_command import libra
from app.bot.commands.escorpio_command import escorpio
from app.bot.commands.sagitario_command import sagitario
from app.bot.commands.capricornio_command import capricornio
from app.bot.commands.acuario_command import acuario
from app.bot.commands.piscis_command import piscis